# Generated by Django 2.2.5 on 2019-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvz', '0002_s_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_register',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
