# Generated by Django 2.2.5 on 2019-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvz', '0003_auto_20191030_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='funclist',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='funclist',
            name='venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funclist',
            name='vnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
