# Generated by Django 2.2.5 on 2019-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvz', '0004_auto_20191030_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_register',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='s_register',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
